name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Set Up MongoDB Server
        run: npm install mongodb-memory-server --save-dev
      - name: Clean workspace
        run: |
          rm -rf node_modules package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "channel": "#hr-server",
              "username": "github-actions",
              "text": "✅ CI build successful for commit <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}> by <${{ github.event.head_commit.author.name }}>",
              "icon_emoji": ":white_check_mark:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "channel": "#hr-server",
              "username": "github-actions",
              "text": "❌ CI build failed for commit <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}> by <${{ github.event.head_commit.author.name }}>",
              "icon_emoji": ":x:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
